name: chomskIE

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  # Core stack
  - python>=3.7
  - nltk
  - spacy
  - numpy
  - ftfy
  - textacy==0.11.0
  - datefinder

  # Visualization stack
  - matplotlib
  - jupyter
